name: pr comment

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - unlocked

jobs:
  pr-comment:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: write-all

    steps:
      - uses: actions/checkout@v3

      - uses: mshick/add-pr-comment@v2
        with:
          repo-token: ${{ secrets.PERSONAL_TOKEN }}
          message-id: pr-test
          message: |
            thanks for opening this pull request and contributing!

            maintainers will review your changes soon. if all is good, it'll be merged.

            meanwhile, the community is welcome to test and share feedback.

            ### ✅ how to confirm it works

            if you tested this pr, please comment:

            ```
            tested and working ✅
            ```

            this helps speed up review and merging.

            ### 📦 how to test this pr locally

            ```
            # npm
            npm install github:AstroX11/user-bot#${{ github.event.pull_request.head.ref }}

            # yarn (v2+)
            yarn add github:AstroX11/user-bot#${{ github.event.pull_request.head.ref }}

            # pnpm
            pnpm add github:AstroX11/user-bot#${{ github.event.pull_request.head.ref }}
            ```

            if you run into any problems or have feedback, just comment here.
